name: "winapps"

volumes:
  data:

services:
  windows:
    image: ghcr.io/dockur/windows@sha256:32cc92715a6c5dc1f63142d3be11059279d64d0faa7519618a07290b3076f9f2
    container_name: WinApps
    env_file:
      - credentials.env
    environment:
      VERSION: "11"
      RAM_SIZE: "${WINAPPS_RAM_SIZE:-8G}"
      CPU_CORES: "${WINAPPS_CPU_CORES:-8}"
      DISK_SIZE: "${WINAPPS_DISK_SIZE:-128G}"
      ALLOCATE: "N"
      HOME: "${HOME}"
    ports:
      - "127.0.0.1:8006:8006"
      - "127.0.0.1:3389:3389/tcp"
      - "127.0.0.1:3389:3389/udp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stop_grace_period: 120s
    restart: on-failure
    volumes:
      - data:/storage
      - ./oem:/oem
    devices:
      - /dev/kvm
      - /dev/net/tun
    group_add:
      - keep-groups
